development:
  google_client_id: <%= ENV["781418970961-2vkjc3p2u94hn1seiq2grdm4r4ked5hm.apps.googleusercontent.com"] %>
  google_client_secret: <%= ENV["CDYeLU7jgdPunmKss0wwpNxD"] %>

  facebook_client_id: <%= ENV["535060867257496"] %>
  facebook_client_secret: <%= ENV["ab6a468becec110914169c216f29f235"] %>